apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/server-deployment.yaml
  - manifests/server-service.yaml
  - manifests/client-deployment.yaml
  - manifests/client-service.yaml
  - manifests/ingress.yaml
images:
  - name: zanaad/markdown-client
    newName: europe-west3-docker.pkg.dev/gke-project-458604/markdown-to-pdf-repo/client
  - name: zanaad/markdown-server
    newName: europe-west3-docker.pkg.dev/gke-project-458604/markdown-to-pdf-repo/server


