apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markdown-to-pdf-ingress
  namespace: markdown-to-pdf
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: markdown-to-pdf-svc
                port:
                  number: 3000