name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: gke-cluster
  GKE_LOCATION: europe-west3
  SERVER_IMAGE: server
  CLIENT_IMAGE: client

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_LOCATION }}'
          project_id: '${{ env.PROJECT_ID }}'

      - name: Build and Push Images
        run: |
          docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$SERVER_IMAGE:$GITHUB_SHA ./server
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$SERVER_IMAGE:$GITHUB_SHA

          docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$CLIENT_IMAGE:$GITHUB_SHA ./client
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$CLIENT_IMAGE:$GITHUB_SHA

      - name: Update Kustomize Images and Deploy
        run: |
          kustomize edit set image zanaad/markdown-server=europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$SERVER_IMAGE:$GITHUB_SHA
          kustomize edit set image zanaad/markdown-client=europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$CLIENT_IMAGE:$GITHUB_SHA

          kubectl apply -k .

          kubectl rollout status deployment markdown-client
          kubectl rollout status deployment markdown-server

          kubectl get services
