name: Deploy to GKE

on:
  push:
    branches:
     - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: gke-cluster
  GKE_LOCATION: europe-west3
  IMAGE: markdown-to-pdf
  BRANCH: ${{ github.ref_name }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_LOCATION }}'
          project_id: '${{ env.PROJECT_ID }}'

      - name: Build and Push Image
        run: |
          docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$IMAGE:$GITHUB_SHA .
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$IMAGE:$GITHUB_SHA


      - name: Deploy with Kustomize
        run: |
          kustomize edit set image zanaad/markdown-to-pdf=europe-west3-docker.pkg.dev/$PROJECT_ID/markdown-to-pdf-repo/$IMAGE:$GITHUB_SHA
          kubectl get namespace markdown-to-pdf || kubectl create namespace markdown-to-pdf
          kubectl apply -k .
          
          # Add this to ensure kubectl uses the correct namespace
          kubectl rollout status deployment markdown-to-pdf -n markdown-to-pdf
          kubectl get services -n markdown-to-pdf

